[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Will-Low <moose.nugget.music@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
base64 = "0.11.0"
